### ISSUE TITLE
Provide a Maven Artifact

### ISSUE THREAD

**Issue by nhatminhle** [nhatminhle/cofoja#2]
_From [michael....@gmail.com](https://code.google.com/u/116684160028903233635/) on February 07, 2011 11:46:13_

Please consider providing Maven artifacts so that mvn driven projects can consume your great work.

_Original issue: http://code.google.com/p/cofoja/issues/detail?id=11_

**Comment by yildiz-online** [comment]
Hi all, for those interested, and if it is ok for you nhatminhle i've created a repo here on github for 1.3

    <repository>
      <id>maven-cofoja-repo</id>
      <url>http://maven-cofoja.github.io/maven</url>
    </repository>

    <dependency>
      <groupId>com.google.java.contract</groupId>
      <artifactId>cofoja</artifactId>
      <version>1.3</version>
    </dependency>

**Comment by exercitussolus** [comment]
Finally! Good to see :-)                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Grégory Van den BorreSent: Freitag, 29. Juli 2016 18:39To: nhatminhle/cofojaReply To: nhatminhle/cofojaSubject: Re: [nhatminhle/cofoja] Provide a Maven Artifact (#2)Hi all, for those interested, and if it is ok for you nhatminhle i've created a repo here on github for 1.3

<repository>
  <id>maven-cofoja-repo</id>
  <url>http://maven-cofoja.github.io/maven</url>
</repository>

<dependency>
  <groupId>com.google.java.contract</groupId>
  <artifactId>cofoja</artifactId>
  <version>1.3</version>
</dependency>


—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by nhatminhle** [comment]
Cofoja is now on Maven Central. See #44
